---
title: "How to adjust malariasimulation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to adjust malariasimulation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Introduction

Now that malariasimulation is public, it may be useful to introduce different functionalities for some interventions or actions that could be explored with this modelling framework. This document presents an example of how to edit the malariasimulation code to introduce habitat management for larval mosquito stages. 

First, assess the function needed statistically to consider whether it can capture the impact of interventions in a reasonable manner. Once happy with understanding how the effect is going to operate, the adaptations to the transmission model code can be made.

### Example: larval source management

In this analysis, trial data from Fillinger et al. (2009) are used that show a percentage reduction in adult mosquito densities that occurred during a larval source habitat management campaign applying Bti larvicide to 3 of 6 villages surveilled in Western Kenya. 

We fitted a function to capture the reduction in mosquitoes

```{r setup, echo=TRUE, eval=FALSE}

lsm_factor = larvi_min + (1.0-larvi_min)*(1+lsm_rate)/(1+lsm_rate*exp(-deprec_param*since_lsm))

```

Here, *larvi_min* is a value between 0 and 1 that, when 1 indicates no reduction in mosquito numbers, and when 0, indicates complete elimination. The parameters *lsm_rate* and *deprec_param* can be used to adjust how rapidly this reduction takes place. 

In the transmission model, the values for this factor multiply the mosquitoes emerging as adults so that, when LSM is on, there will be progressively fewer mosquitoes until the threshold (equal to *larvi_min*) is reached.

Therefore, we can consider this to impact on the SIR equations for adult mosquitoes:

```{echo=TRUE, eval=FALSE}

dS/dt =   0.5/emerging_pupae * lsm_factor - (mum + foim) * S

```


So, this is a relatively simple change that we can make to the transmission model code in malariasimulation.

### Model files requiring adjustments

To do this, we need to adjust the cpp code for adult mosquitoes (**adult_mosquito_eqs.cpp**)
And corresponding code to define what we will change (**adult_mosquito_eqs.h**)

We also need to change the R code in the vector control related files. 
These are:
**biting_process.R**
**compartmental.R**
**vector_control.R**
**vector_control_parameters.R**

For the individual mosquito model, we need to modify a little more. We would need to adjust **mosquito_biology.R** and to pass all of the model parameters into the **create_mosquito_emergence_process** function. We'd also want to be careful to calculate the lsm_factor for each species and combine them with the p_counts correctly. We are not making adjustments for the individual mosquito model here. 

For the compartmental mosquito model we will run through the changes in turn. 


#### CPP code: adult_mosquito_eqs.cpp

The change to the model is very simple, but we need to add this to the **adult_mosquito_eqs.cpp**
We add the lsm_factor into the *AdultMosquitoModel*

```{echo=TRUE, eval=FALSE}

AdultMosquitoModel::AdultMosquitoModel(
    AquaticMosquitoModel growth_model,
    double mu,
    double tau,
    double incubating,
    double foim,
    double lsm_factor
    ) : growth_model(growth_model), mu(mu), tau(tau), foim(foim), lsm_factor(lsm_factor)
{
    for (auto i = 0u; i < tau; ++i) {
        lagged_incubating.push(incubating);
    }
}

```

And we add the *lsm_factor* to the growth of adult females. In cpp the convention is to define this in as *model.lsm_factor*

```{echo=TRUE, eval=FALSE}

        dxdt[get_idx(AdultState::S)] =
            .5 * model.lsm_factor * x[get_idx(AquaticState::P)] / model.growth_model.dp //growth to adult female
            - x[get_idx(AdultState::S)] * model.foim //infections
            - x[get_idx(AdultState::S)] * model.mu; //deaths   

```

And we need to update this through the code:

```{echo=TRUE, eval=FALSE}
//[[Rcpp::export]]
Rcpp::XPtr<AdultMosquitoModel> create_adult_mosquito_model(
    Rcpp::XPtr<AquaticMosquitoModel> growth_model,
    double mu,
    double tau,
    double susceptible,
    double foim,
    double lsm_factor
    ) {
    auto model = new AdultMosquitoModel(
        *growth_model,
        mu,
        tau,
        susceptible,
        foim,
        lsm_factor
    );
    return Rcpp::XPtr<AdultMosquitoModel>(model, true);
}

//[[Rcpp::export]]
void adult_mosquito_model_update(
    Rcpp::XPtr<AdultMosquitoModel> model,
    double mu,
    double foim,
    double lsm_factor,
    double susceptible,
    double f
    ) {
    model->mu = mu;
    model->foim = foim;
    model->lsm_factor = lsm_factor;
    model->growth_model.f = f;
    model->growth_model.mum = mu;
    model->lagged_incubating.push(susceptible * foim);
    if (model->lagged_incubating.size() > 0) {
        model->lagged_incubating.pop();
    }
}
```


#### CPP code: adult_mosquito_eqs.h
In cpp, we have to define each entity prior to using it, so we also need to adjust the **adult_mosquito_eqs.h**

```{echo=TRUE, eval=FALSE}
/*
 * AdultMosquitoModel
 *
 * A data structure for storing equation parameters for each timestep
 * 
 * foim, mu and lagged_incubating are updated each timestep
 */
struct AdultMosquitoModel {
    AquaticMosquitoModel growth_model;
    std::queue<double> lagged_incubating; //last tau values for incubating mosquitos
    double mu; //death rate for adult female mosquitoes
    const double tau; //extrinsic incubation period
    double foim; //force of infection towards mosquitoes
    double lsm_factor; //reduced hatching due to some larval habitat mitigation
    AdultMosquitoModel(AquaticMosquitoModel, double, double, double, double, double);
};
```

These changes will automatically be integrated into the **RcppExports.cpp** file.



#### R code: vector_control.R

First, we add in a function to define the *lsm_factor*. This is put into **vector_control.R** 

We define a title and give the function a description, and relevant parameters 
```{echo=TRUE, eval=FALSE}

#' @title Distribute larval source habitat management
#' @description simulates larval source management by reducing recruitment to adult female mosquitoes 
#' from `set_habitat_management` and correlation parameters from
#' `get_correlation_parameters`
#'
#' @param variables list of variables in the model
#' @param larvi_min is the fractional reduction in adult females joining susceptible population 
#' @param habitat_management_timesteps the time when this is switched on 
#' @param parameters the model parameters
#' @param correlations correlation parameters
#' @noRd

```

Next we code in the function that will return the altered impact after a time when the intervention is switched on. If the lsm is not operating we turn this off by allowing *lsm_factor* to equal 1. As this factor multiplies the Susceptible female adult mosquitoes emerging from pupae, a value of 1 should be our default and return the same as for the situation without larval source management. 

```{echo=TRUE, eval=FALSE}
lsm_factor <- function(
  timestep,
  species,
  parameters
) {
  if (parameters$habitat_management) {
    larvi_min <- parameters$larvi_min[[species]]
    lsm_rate <- parameters$lsm_rate[[species]]
    deprec_param <- parameters$deprec_param[[species]]
    i <- match_timestep(parameters$habitat_management_timesteps,timestep)
    lsm_time <- parameters$habitat_management_timesteps[i]
    since_lsm <- timestep - lsm_time
    if (since_lsm < 0) {
      return(1)
    }
    return(larvi_min + (1.0-larvi_min)*(1+lsm_rate)/(1+lsm_rate*exp(-deprec_param*since_lsm)))
  
  } 
  return(1)
}


```


#### R code: vector_control_parameters.R

We then want to make it straight forward for the user to turn this intervention on or off, so we create a function to do this in **vector_control_parameters.R**

Again, we define a title, description and parameters and include:

```{echo=TRUE, eval=FALSE}
#' @export
```

which makes this accessible.


```{echo=TRUE, eval=FALSE}

#' @title Parameterise a habitat management strategy
#'
#' @description The model will simulate larval source habitat management at 
#' `timesteps` to the entire human population. 
#' The impact will reduce adult mosquitoes recruited from pupae to the susceptible
#' cohort.
#'
#' The rapidity of the impact is captured by the lsm_factor function
#' by changing the parameters lsm_rate and deprec_param
#'
#' The amount of impact in terms of reduced adult mosquito densities
#' that the habitat management has is determined by larvi_min which is
#' set to 1 as default when there is no impact.
#'
#' Habitat management effects will be randomly removed each timestep with a rate of `1 -
#' exp(-1/habitat_management_waning)`
#'
#' The structure for the habitat model is documented in the
#' working draft Sherrard-Smith et al (larviciding in Kenya)
#'
#' @param parameters a list of parameters to modify
#' @param timesteps the timesteps at which to distribute lsm rounds
#' @param larvi_min the proportion of the mosquito population reduced (0 to 1), 1 is no impact
#' @param lsm_rate the duration til the impact is acheived
#' @param deprec_param the speed on impact taking mosquito densities down to new-normal 
#' @param habitat_management_waning the average number of timesteps LSM works for
#' With nrows=length(timesteps), ncols=length(species)
#' @param larvi_min a matrix of reduction probabilities for each species over time
#' With nrows=length(timesteps), ncols=length(species)
#' @param lsm_rate a matrix of reduction probabilities for each species over time
#' With nrows=length(timesteps), ncols=length(species)
#' @param deprec_param a matrix of reduction probabilities for each species over time
#' @export
set_habitat_management <- function(
  parameters,
  timesteps,
  larvi_min,
  lsm_rate,
  deprec_param
  ) {
  for (x in list(larvi_min, lsm_rate, deprec_param)) {
    if (ncol(x) != length(parameters$species)) {
      stop('habitat management probabilities rows need to align with species')
    }
    if (nrow(x) != length(1)) {
      stop('habitat management probabilities columns need to be 1')
    }
  }
  parameters$habitat_management <- TRUE
  parameters$habitat_management_timesteps <- timesteps
  parameters$larvi_min <- larvi_min
  parameters$lsm_rate <- lsm_rate
  parameters$deprec_param <- deprec_param
  parameters
}


```


#### R code: compartmental.R

We need to update the **compartmental.R** file to acknowledge the new factor *lsm_factor* within the *create_adult_mosquito_model* function.

```{echo=TRUE, eval=FALSE}
parameterise_mosquito_models <- function(parameters) {
  lapply(
    seq_along(parameters$species),
    function(i) {
      p <- parameters$species_proportions[[i]]
      m <- p * parameters$total_M
      growth_model <- create_aquatic_mosquito_model(
        parameters$beta,
        parameters$del,
        parameters$me,
        calculate_carrying_capacity(parameters, m, i),
        parameters$gamma,
        parameters$dl,
        parameters$ml,
        parameters$dpl,
        parameters$mup,
        m,
        parameters$model_seasonality,
        parameters$g0,
        parameters$g,
        parameters$h,
        calculate_R_bar(parameters),
        parameters$mum[[i]],
        parameters$blood_meal_rates[[i]],
        parameters$rainfall_floor
      )

      if (!parameters$individual_mosquitoes) {
        susceptible <- initial_mosquito_counts(
          parameters,
          i,
          parameters$init_foim,
          m
        )[ADULT_ODE_INDICES['Sm']]
        return(
          create_adult_mosquito_model(
            growth_model,
            parameters$mum[[i]],
            parameters$dem,
            susceptible * parameters$init_foim,
            parameters$init_foim,
            lsm_factor(0,i,parameters)
          )
        )
      }
      growth_model
    }
  )
}

```


#### R code: biting_process.R

And, the biting process:

```{echo=TRUE, eval=FALSE}
adult_mosquito_model_update(
        models[[s_i]],
        mu,
        foim,
        lsm_factor(timestep,s_i,parameters),
        solver_states[[ADULT_ODE_INDICES['Sm']]],
        f
      )
```

