---
title: "Human_Interventions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Human Interventions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
suppressPackageStartupMessages(library(ggplot2))
library(malariasimulation)
library(malariaEquilibrium)
library(reshape2)
suppressPackageStartupMessages(library(cowplot))
```

# Equilibrium testing

Malaria treatment can be compared to the equilibrium solution.

Let's parameterise our model...

```{r}
year <- 365
sim_length <- 50 * year
human_population <- 1000
repetitions <- 5

remove_keys <- function(x, n) { for (name in n) { x[[name]] <- NULL }; x }

jamie_params <- load_parameter_set("Jamie_parameters.rds")

params <- remove_keys(
  jamie_params,
  c(
    'tl', # unused!
    'aA', # used for microscopy and pcr calculations
    'aU', # used for microscopy and pcr calculations
    'tau',# unused!
    'f', # used later to calculate blood_meal_rates
    'Q0', # used later to calculate blood_meal_rates
    'cd_w', # unused!
    'cd_p' # unused!
  )
)

simparams <- translate_jamie(params)
simparams[['human_population']] <- human_population

#parameterise single species
simparams$variety_proportions <- 1
simparams$blood_meal_rates <- jamie_params$f * jamie_params$Q0

#use the ode vector model
simparams$vector_ode <- TRUE
```

Now we can write some utility functions for running our simulation:

```{r}
estimate_eir <- function() {
  output <- run_simulation(sim_length, simparams)
  sum(tail(output$mean_EIR, year))
}

get_equilibrium <- function(EIR, ft = 0) {
  human_equilibrium(EIR = EIR, ft = ft, p = jamie_params, age = 0:99)
}

get_state_proportions <- function(eq) colSums(eq$states[,c('S', 'D', 'A', 'U', 'T', 'P')])
```

Then we can run the simulation over a variety of densities and ft:

```{r}
estimated_eirs <- c()
outputs <- list()
labels <- list()
for (density in c(.5, 1, 5, 10, 50, 100, 500, 1000)) {
  for (ft in c(.25, .5, .75)) {
    simparams$density <- density
    simparams$ft <- ft
    EIR <- estimate_eir()
    if (EIR > 0) {
      estimated_eirs <- c(estimated_eirs, EIR)
      eq <- get_equilibrium(EIR, ft)
      simparams <- parameterise_equilibrium(get_state_proportions(eq), simparams)
      output <- run_simulation_with_repetitions(
        sim_length,
        repetitions,
        simparams,
        parallel=TRUE
      )
      outputs[[length(outputs) + 1]] <- output
      labels[[length(labels) + 1]] <- list(density = density, ft = ft)
    }
  }
}
```

Let's plot the agreement in state proportions:

```{r, fig.height = 12}

agreement_plots <- lapply(
  seq_along(outputs),
  function(i) {
    output <- outputs[[i]]
    pop_size <- simparams$human_population
    state_props <- get_state_proportions(get_equilibrium(estimated_eirs[[i]]))
    equilibrium <- data.frame(
      timestep = seq(sim_length),
      human_S_count = rep(state_props[['S']] * pop_size, sim_length),
      human_D_count = rep(state_props[['D']] * pop_size, sim_length),
      human_A_count = rep(state_props[['A']] * pop_size, sim_length),
      human_U_count = rep(state_props[['U']] * pop_size, sim_length),
      human_Tr_count = rep(state_props[['T']] * pop_size, sim_length),
      human_Ph_count = rep(state_props[['P']] * pop_size, sim_length)
    )
    ggplot(
      melt(
        output[c(
          'timestep',
          'repetition',
          'human_S_count',
          'human_D_count',
          'human_A_count',
          'human_U_count',
          'human_Tr_count',
          'human_Ph_count'
        )],
        id.vars=c('timestep', 'repetition')
      )
    ) + geom_line(
      aes(
        x = timestep,
        y = value,
        group = interaction(variable, repetition),
        color = variable,
        alpha = 1/repetitions
      )
    ) + geom_line(
      data = melt(equilibrium, 'timestep'),
      aes(x = timestep, y = value, group = variable, color = variable),
      linetype = 'dashed'
    )
  }
)

# consolidate legends
legend <- get_legend(agreement_plots[[1]])
agreement_plots <- lapply(
  agreement_plots,
  function(plot) plot + theme(legend.position="none")
)

plot_grid(
  plot_grid(
    plotlist = agreement_plots,
    labels = vapply(
      labels,
      function(l) paste0('d=', l$density, ',ft=', l$ft),
      character(1)
    ),
    ncol = 2
  ),
  legend,
  rel_widths = c(1, .1)
)
```

Let's plot the effect of ft on the relationship between EIR and PfPrev2-10:

```{r}
eirs <- vapply(
  outputs,
  function(output) {
    mean(vapply(
      seq(repetitions),
      function(r) {
        sum(tail(subset(output, output$repetition == r)$mean_EIR, year))
      },
      numeric(1)
    ))
  },
  numeric(1)
)

prevs <- vapply(
  outputs,
  function(output) {
    mean(vapply(
      seq(repetitions),
      function(r) {
        mean(
          tail(
            subset(output, output$repetition == r)$prev_2_10,
            year
          )
        ) / simparams$human_population
      },
      numeric(1)
    ))
  },
  numeric(1)
)

fts <- vapply(labels, function(label) label$ft, numeric(1))

ggplot(
  data.frame(eir = eirs, prev = prevs, ft = fts)
) + geom_line(
  aes(x = eir, y = prev, group = ft, colour = ft)
) + scale_x_continuous(trans='log10')
```