# Dockerfile with development tools for:
# easy testing, documentation generation and benchmarking
FROM rocker/r-ver:4.0.2

RUN apt-get update && apt-get -y install \
  texlive-latex-base \
  texlive-fonts-extra \
  texinfo

RUN R -e "install.packages(c('remotes', 'testthat'))"

COPY DESCRIPTION /home/docker/ms/

RUN R -e "remotes::install_deps('/home/docker/ms', dependencies = TRUE)"
