/*
 * Please do not edit this file -- it ensures that your package will export a
 * 'run_testthat_tests()' C routine that can be used to run the Catch unit tests
 * available in your package.
 */
#define TESTTHAT_TEST_RUNNER
#include <testthat.h>
#include <gmock/gmock.h>
#include <gtest/gtest.h>

//' @export
void setup_gmock() {
  ::testing::GTEST_FLAG(throw_on_failure) = true;
  int argc = 0;
  char** argv = nullptr;
  ::testing::InitGoogleMock(&argc, argv);
}
