# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Mosquito births
#' @description
#' This is the process for mosquito birth, it defines how many new early stage
#' larvae are created on each timestep.
#' @param mosquito the mosquito individual
#' @param susceptable the susceptable mosquito state
#' @param infected the infected mosquito state
#' @param unborn the unborn mosquito state
#' @param early_larval_stage the early stage larval state
#' @param larval_growth_event the event to transition from early to late larval stage
create_egg_laying_process_cpp <- function(mosquito, susceptable, infected, unborn, early_larval_stage, larval_growth_event) {
    .Call(`_malariasimulation_create_egg_laying_process_cpp`, mosquito, susceptable, infected, unborn, early_larval_stage, larval_growth_event)
}

