# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

carrying_capacity <- function(timestep, model_seasonality, days_per_timestep, g0, g, h, K0, R_bar) {
    .Call(`_malariasimulation_carrying_capacity`, timestep, model_seasonality, days_per_timestep, g0, g, h, K0, R_bar)
}

rainfall <- function(t, days_per_timestep, g0, g, h) {
    .Call(`_malariasimulation_rainfall`, t, days_per_timestep, g0, g, h)
}

#' @title Mosquito births
#' @description
#' This is the process for mosquito birth, it defines how many new early stage
#' larvae are created on each timestep.
#' @param mosquito the mosquito individual
#' @param susceptable the susceptable mosquito state
#' @param incubating the incubating mosquito state
#' @param infected the infected mosquito state
#' @param unborn the unborn mosquito state
#' @param early_larval_stage the early stage larval state
create_egg_laying_process_cpp <- function(mosquito, susceptable, incubating, infected, unborn, early_larval_stage) {
    .Call(`_malariasimulation_create_egg_laying_process_cpp`, mosquito, susceptable, incubating, infected, unborn, early_larval_stage)
}

create_larval_death_process_cpp <- function(mosquito, early_larval_stage, late_larval_stage, unborn, K0, R_bar) {
    .Call(`_malariasimulation_create_larval_death_process_cpp`, mosquito, early_larval_stage, late_larval_stage, unborn, K0, R_bar)
}

create_mosquito_model <- function(init, beta, de, mue, K0, gamma, dl, mul, dp, mup, foim, mu, tau, model_seasonality, days_per_timestep, g0, g, h, R_bar) {
    .Call(`_malariasimulation_create_mosquito_model`, init, beta, de, mue, K0, gamma, dl, mul, dp, mup, foim, mu, tau, model_seasonality, days_per_timestep, g0, g, h, R_bar)
}

mosquito_model_step <- function(model, foim) {
    invisible(.Call(`_malariasimulation_mosquito_model_step`, model, foim))
}

mosquito_model_get_states <- function(model) {
    .Call(`_malariasimulation_mosquito_model_get_states`, model)
}

