# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Mosquito emergence process
#' @description Move mosquitos from Unborn to Sm in line with the number of
#' pupals in the ODE models
#'
#' @param mosquito the handle for the mosquito individual
#' @param odes a list of odes for each species
#' @param unborn the handle for the unborn mosquito state
#' @param susceptible the handle for the susceptible mosquito state
#' @param variety the handle for the variable representing the mosquito species
#' @param dpl the delay for pupal growth (in timesteps)
create_mosquito_emergence_process_cpp <- function(mosquito, odes, unborn, susceptible, variety, dpl) {
    .Call(`_malariasimulation_create_mosquito_emergence_process_cpp`, mosquito, odes, unborn, susceptible, variety, dpl)
}

#' @title Mosquito infection process
#' @description
#' This is the process of infection for mosquitos. It results in a state
#' transition from Sm to Pm for infected mosquitos.
#'
#' NOTE: this process will become obsolete when the model is reformulated to
#' model individual mosquitos biting individual humans.
#' @param mosquito the mosquito individual
#' @param human the human individual
#' @param states a list of relevant model states (Sm, Pm)
#' @param variables a list of relevant model variables (birth, zeta, infectivity, mosquito_variety)
create_mosquito_infection_process_cpp <- function(mosquito, human, states, variables) {
    .Call(`_malariasimulation_create_mosquito_infection_process_cpp`, mosquito, human, states, variables)
}

create_mosquito_model <- function(init, beta, de, mue, K0, gamma, dl, mul, dp, mup, total_M) {
    .Call(`_malariasimulation_create_mosquito_model`, init, beta, de, mue, K0, gamma, dl, mul, dp, mup, total_M)
}

mosquito_model_get_states <- function(model) {
    .Call(`_malariasimulation_mosquito_model_get_states`, model)
}

#' @title Step mosquito ODE
#' @description collects summarises the human state, sends it to the vector ode
#' and makes a step
#'
#' @param odes the models to step, one for each species
#' @param mosquito the mosquito individual handle
#' @param states a list of all of adult mosquito states (Sm, Pm, Im)
#' @param variety the handle for the mosquito variety variable
create_ode_stepping_process_cpp <- function(odes, mosquito, states, variety) {
    .Call(`_malariasimulation_create_ode_stepping_process_cpp`, odes, mosquito, states, variety)
}

mosquito_model_step <- function(model, total_M) {
    invisible(.Call(`_malariasimulation_mosquito_model_step`, model, total_M))
}

